import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import * as XLSX from "xlsx";
import onboardingService from "../services/onboarding.service.js";

const CATEGORIAS_INICIALES = [{ nombre: "Comidas", tipo: "comida" }, { nombre: "Bebidas", tipo: "bebida" }];
const PAGOS_INICIALES = [{ nombre: "Efectivo", tipo: "efectivo" }, { nombre: "Tarjeta", tipo: "tarjeta" }];

function leerArchivoTabla(archivo) {
  return archivo.arrayBuffer().then((buffer) => {
    const libro = XLSX.read(buffer, { type: "array" });
    const hoja = libro.Sheets[libro.SheetNames[0]];
    return XLSX.utils.sheet_to_json(hoja, { defval: "" });
  });
}

export default function Onboarding() {
  const navigate = useNavigate();
  const [datos, setDatos] = useState(null); const [paso, setPaso] = useState("negocio"); const [error, setError] = useState(""); const [mensaje, setMensaje] = useState(""); const [guardando, setGuardando] = useState(false); const [tour, setTour] = useState(false);
  const [negocio, setNegocio] = useState({}); const [cantidadMesas, setCantidadMesas] = useState(0); const [categorias, setCategorias] = useState(CATEGORIAS_INICIALES); const [pagos, setPagos] = useState(PAGOS_INICIALES); const [impresoras, setImpresoras] = useState([]);
  const cargar = async () => { try { const respuesta = await onboardingService.obtener(); setDatos(respuesta); setNegocio(respuesta.restaurante); setCantidadMesas(respuesta.mesas.length); setCategorias(respuesta.categorias.length ? respuesta.categorias : CATEGORIAS_INICIALES); setPagos(respuesta.restaurante.metodosPago.length ? respuesta.restaurante.metodosPago : PAGOS_INICIALES); setImpresoras(respuesta.restaurante.impresoras); } catch (e) { setError(e.response?.data?.error || "No se pudo cargar la configuración inicial."); } };
  useEffect(() => { cargar(); }, []);
  const ejecutar = async (accion, exito) => { setGuardando(true); setError(""); try { await accion(); setMensaje(exito); await cargar(); } catch (e) { setError(e.response?.data?.error || "No se pudo guardar el paso."); } finally { setGuardando(false); } };
  const cargarLogo = (archivo) => { if (!archivo) return; if (!archivo.type.startsWith("image/")) { setError("Elegí un archivo de imagen."); return; } const reader = new FileReader(); reader.onload = () => setNegocio({ ...negocio, logoUrl: reader.result }); reader.readAsDataURL(archivo); };
  const importarProductos = async (archivo) => { try { const filas = await leerArchivoTabla(archivo); await ejecutar(() => onboardingService.importarProductos(filas), `Importación finalizada: ${filas.length} filas procesadas.`); } catch { setError("No se pudo leer el archivo. Usá CSV o Excel con encabezados como nombre, categoria y precio."); } };
  const importarClientes = async (archivo) => { try { const csv = await archivo.text(); await ejecutar(() => onboardingService.importarClientes(csv), "Clientes importados correctamente."); } catch { setError("No se pudo leer el CSV de clientes."); } };
  const editarLista = (lista, setLista, indice, campo, valor) => setLista(lista.map((item, i) => i === indice ? { ...item, [campo]: valor } : item));
  if (!datos) return <div className="page-header"><div><h1>Preparando tu espacio</h1><p>{error || "Cargando configuración inicial..."}</p></div></div>;
  const secciones = [{ clave: "negocio", texto: "Negocio" }, { clave: "operacion", texto: "Operación" }, { clave: "catalogo", texto: "Catálogo" }, { clave: "equipo", texto: "Equipo" }, { clave: "finalizar", texto: "Finalizar" }];
  return <section className="onboarding-page"><div className="page-header"><div><div className="page-title">Puesta en marcha</div><div className="page-subtitle">Configurá tu restaurante y empezá a vender.</div></div><button className="btn btn-outline-secondary" onClick={() => setTour(true)}><i className="fas fa-map me-2" />Ver tour</button></div><div className="row g-4"><aside className="col-lg-3"><div className="card"><div className="card-body"><div className="d-grid gap-1">{secciones.map((item) => <button key={item.clave} className={`btn text-start ${paso === item.clave ? "btn-primary" : "btn-light"}`} onClick={() => setPaso(item.clave)}>{item.text}</button>)}</div><hr />{datos.pasos.map((item) => <div key={item.clave} className="d-flex align-items-center gap-2 small mb-2"><i className={`fas ${item.listo ? "fa-check-circle text-success" : "fa-circle text-muted"}`} />{item.titulo}</div>)}</div></div></aside><main className="col-lg-9">{error && <div className="alert alert-danger">{error}</div>}{mensaje && <div className="alert alert-success">{mensaje}</div>}
  {paso === "negocio" && <div className="card"><div className="card-body"><h1 className="h4">Datos comerciales</h1><div className="row g-3 mt-1"><div className="col-md-6"><label className="form-label">Nombre comercial</label><input className="form-control" value={negocio.nombre || ""} onChange={(e) => setNegocio({ ...negocio, nombre: e.target.value })} /></div><div className="col-md-3"><label className="form-label">Moneda</label><select className="form-select" value={negocio.moneda || "ARS"} onChange={(e) => setNegocio({ ...negocio, moneda: e.target.value })}><option value="ARS">ARS</option><option value="USD">USD</option><option value="UYU">UYU</option></select></div><div className="col-md-3"><label className="form-label">País</label><select className="form-select" value={negocio.pais || "AR"} onChange={(e) => setNegocio({ ...negocio, pais: e.target.value })}><option value="AR">Argentina</option><option value="UY">Uruguay</option><option value="CL">Chile</option></select></div><div className="col-md-6"><label className="form-label">Zona horaria</label><input className="form-control" value={negocio.zonaHoraria || ""} onChange={(e) => setNegocio({ ...negocio, zonaHoraria: e.target.value })} /></div><div className="col-md-3"><label className="form-label">Impuesto (%)</label><input type="number" min="0" max="100" className="form-control" value={negocio.porcentajeImpuesto ?? 0} onChange={(e) => setNegocio({ ...negocio, porcentajeImpuesto: e.target.value })} /></div><div className="col-md-3"><label className="form-label">Logo</label><input className="form-control" type="file" accept="image/*" onChange={(e) => cargarLogo(e.target.files[0])} /></div><div className="col-md-6"><label className="form-label">Razón social</label><input className="form-control" value={negocio.razonSocial || ""} onChange={(e) => setNegocio({ ...negocio, razonSocial: e.target.value })} /></div><div className="col-md-6"><label className="form-label">CUIT / Identificación fiscal</label><input className="form-control" value={negocio.identificacionFiscal || ""} onChange={(e) => setNegocio({ ...negocio, identificacionFiscal: e.target.value })} /></div><div className="col-md-6"><label className="form-label">Email comercial</label><input className="form-control" type="email" value={negocio.emailComercial || ""} onChange={(e) => setNegocio({ ...negocio, emailComercial: e.target.value })} /></div><div className="col-md-6"><label className="form-label">Teléfono</label><input className="form-control" value={negocio.telefono || ""} onChange={(e) => setNegocio({ ...negocio, telefono: e.target.value })} /></div></div><button className="btn btn-primary mt-4" disabled={guardando} onClick={() => ejecutar(() => onboardingService.actualizarNegocio(negocio), "Datos comerciales guardados.")}>Guardar y continuar</button></div></div>}
  {paso === "operacion" && <div className="d-grid gap-4"><div className="card"><div className="card-body"><h1 className="h4">Mesas</h1><p className="text-muted">Actualmente hay {datos.mesas.length} mesas creadas.</p><div className="input-group" style={{ maxWidth: 300 }}><input type="number" min="0" max="250" className="form-control" value={cantidadMesas} onChange={(e) => setCantidadMesas(e.target.value)} /><button className="btn btn-primary" disabled={guardando} onClick={() => ejecutar(() => onboardingService.guardarMesas(cantidadMesas), "Mesas configuradas.")}>Guardar</button></div></div></div><div className="card"><div className="card-body"><h1 className="h4">Métodos de pago</h1>{pagos.map((pago, i) => <div className="row g-2 mb-2" key={i}><div className="col"><input className="form-control" value={pago.nombre} onChange={(e) => editarLista(pagos, setPagos, i, "nombre", e.target.value)} /></div><div className="col"><select className="form-select" value={pago.tipo} onChange={(e) => editarLista(pagos, setPagos, i, "tipo", e.target.value)}><option value="efectivo">Efectivo</option><option value="tarjeta">Tarjeta</option><option value="transferencia">Transferencia</option><option value="billetera">Billetera</option></select></div></div>)}<button className="btn btn-light me-2" onClick={() => setPagos([...pagos, { nombre: "", tipo: "efectivo" }])}>Agregar</button><button className="btn btn-primary" disabled={guardando} onClick={() => ejecutar(() => onboardingService.guardarMetodosPago(pagos), "Métodos de pago guardados.")}>Guardar</button></div></div><div className="card"><div className="card-body"><h1 className="h4">Impresoras</h1><p className="text-muted">Podés omitir este paso y configurarlo más tarde.</p>{impresoras.map((impresora, i) => <div className="row g-2 mb-2" key={i}><div className="col"><input className="form-control" placeholder="Nombre" value={impresora.nombre} onChange={(e) => editarLista(impresoras, setImpresoras, i, "nombre", e.target.value)} /></div><div className="col"><select className="form-select" value={impresora.destino} onChange={(e) => editarLista(impresoras, setImpresoras, i, "destino", e.target.value)}><option value="cocina">Cocina</option><option value="caja">Caja</option><option value="barra">Barra</option></select></div></div>)}<button className="btn btn-light me-2" onClick={() => setImpresoras([...impresoras, { nombre: "", destino: "cocina", tipoConexion: "red" }])}>Agregar impresora</button><button className="btn btn-primary" disabled={guardando} onClick={() => ejecutar(() => onboardingService.guardarImpresoras(impresoras), "Impresoras guardadas.")}>Guardar</button></div></div></div>}
  {paso === "catalogo" && <div className="d-grid gap-4"><div className="card"><div className="card-body"><h1 className="h4">Categorías</h1>{categorias.map((categoria, i) => <div className="row g-2 mb-2" key={i}><div className="col"><input className="form-control" value={categoria.nombre} onChange={(e) => editarLista(categorias, setCategorias, i, "nombre", e.target.value)} /></div><div className="col"><select className="form-select" value={categoria.tipo} onChange={(e) => editarLista(categorias, setCategorias, i, "tipo", e.target.value)}><option value="comida">Comida</option><option value="bebida">Bebida</option><option value="desayuno">Desayuno</option></select></div></div>)}<button className="btn btn-light me-2" onClick={() => setCategorias([...categorias, { nombre: "", tipo: "comida" }])}>Agregar</button><button className="btn btn-primary" disabled={guardando} onClick={() => ejecutar(() => onboardingService.guardarCategorias(categorias), "Categorías guardadas.")}>Guardar categorías</button></div></div><div className="card"><div className="card-body"><h1 className="h4">Importar productos</h1><p className="text-muted">Subí CSV o Excel con columnas: nombre, categoria, precio, precioSalon, costo y stockActual.</p><input className="form-control" type="file" accept=".csv,.xlsx,.xls" onChange={(e) => e.target.files[0] && importarProductos(e.target.files[0])} /></div></div><div className="card"><div className="card-body"><h1 className="h4">Importar clientes</h1><p className="text-muted">Subí un CSV con nombre, apellido, teléfono y email.</p><input className="form-control" type="file" accept=".csv,text/csv" onChange={(e) => e.target.files[0] && importarClientes(e.target.files[0])} /></div></div></div>}
  {paso === "equipo" && <div className="card"><div className="card-body"><h1 className="h4">Invitá a tu equipo</h1><p className="text-muted">Asigná roles para caja, cocina, salón y administración. Cada persona recibe un enlace seguro para activar su cuenta.</p><Link className="btn btn-primary" to="/usuarios">Gestionar usuarios</Link></div></div>}
  {paso === "finalizar" && <div className="card"><div className="card-body"><h1 className="h4">Todo listo para empezar</h1><p className="text-muted">Podés volver a esta configuración desde el menú cuando lo necesites.</p><button className="btn btn-primary" disabled={guardando} onClick={() => ejecutar(async () => { await onboardingService.completar(); setTour(true); }, "Configuración inicial completada.")}>Finalizar puesta en marcha</button></div></div>}
  </main></div>{tour && <div className="modal-backdrop show" style={{ display: "block" }}><div className="modal d-block" tabIndex="-1"><div className="modal-dialog modal-dialog-centered"><div className="modal-content"><div className="modal-header"><h2 className="modal-title h5">Recorrido rápido</h2><button className="btn-close" onClick={() => setTour(false)} /></div><div className="modal-body"><p><strong>Salón y Caja:</strong> abrí el turno, tomá pedidos y registrá cobros.</p><p><strong>Cocina:</strong> seguí las comandas y avanzá sus estados.</p><p><strong>Backoffice:</strong> revisá ventas, productos y reportes.</p></div><div className="modal-footer"><button className="btn btn-light" onClick={() => setTour(false)}>Quedarme aquí</button><button className="btn btn-primary" onClick={() => navigate("/salon")}>Ir a vender</button></div></div></div></div></div>}</section>;
}
