import React, { useEffect, useState } from "react";
import axios from "../services/axios.config.js";

export default function Usuarios() {
  const [usuarios, setUsuarios] = useState([]); const [roles, setRoles] = useState([]); const [error, setError] = useState(""); const [invitacion, setInvitacion] = useState({ nombre: "", email: "", usuario: "", rol: "mozo" });
  const cargar = async () => { try { const [lista, config] = await Promise.all([axios.get("/usuarios"), axios.get("/usuarios/config/roles")]); setUsuarios(lista.data); setRoles(config.data.roles); } catch (e) { setError(e.response?.data?.error || "No se pudo cargar la administración de usuarios"); } };
  useEffect(() => { cargar(); }, []);
  const invitar = async (e) => { e.preventDefault(); try { await axios.post("/usuarios/invitaciones", invitacion); setInvitacion({ nombre: "", email: "", usuario: "", rol: "mozo" }); await cargar(); } catch (e) { setError(e.response?.data?.error || "No se pudo enviar la invitación"); } };
  const cambiarRol = async (id, rol) => { try { await axios.patch(`/usuarios/${id}/rol`, { rol }); await cargar(); } catch (e) { setError(e.response?.data?.error || "No se pudo actualizar el rol"); } };
  return <section><div className="page-header"><div><h1>Usuarios y permisos</h1><p>Administrá accesos, roles y colaboradores del restaurante.</p></div></div>{error && <div className="alert alert-danger">{error}</div>}<div className="row g-4"><div className="col-lg-7"><div className="card"><div className="card-body p-0"><div className="table-responsive"><table className="table mb-0"><thead><tr><th>Usuario</th><th>Rol</th><th>Estado</th></tr></thead><tbody>{usuarios.map((usuario) => <tr key={usuario.id}><td><strong>{usuario.nombre || usuario.usuario}</strong><br /><small>{usuario.email || usuario.usuario}</small></td><td><select className="form-select form-select-sm" value={usuario.roles[0] || ""} onChange={(e) => cambiarRol(usuario.id, e.target.value)}>{roles.map((rol) => <option key={rol.id} value={rol.clave}>{rol.nombre}</option>)}</select></td><td>{usuario.emailVerificado ? "Activo" : "Pendiente"}</td></tr>)}</tbody></table></div></div></div></div><div className="col-lg-5"><div className="card"><div className="card-body"><h2 className="h5">Invitar usuario</h2><form onSubmit={invitar} className="d-grid gap-3">{[["nombre", "Nombre"], ["email", "Email"], ["usuario", "Usuario"]].map(([campo, etiqueta]) => <input key={campo} className="form-control" placeholder={etiqueta} value={invitacion[campo]} onChange={(e) => setInvitacion({ ...invitacion, [campo]: e.target.value })} required={campo === "email"} />)}<select className="form-select" value={invitacion.rol} onChange={(e) => setInvitacion({ ...invitacion, rol: e.target.value })}>{roles.map((rol) => <option key={rol.id} value={rol.clave}>{rol.nombre}</option>)}</select><button className="btn btn-primary">Enviar invitación</button></form></div></div></div></div></section>;
}
