import React, { useEffect, useState } from "react";
import axios from "../services/axios.config.js";

const inicial = { nombre: "", usuario: "", email: "", contrasena: "", rol: "mozo" };

export default function Usuarios() {
  const [usuarios, setUsuarios] = useState([]); const [roles, setRoles] = useState([]); const [nuevo, setNuevo] = useState(inicial); const [error, setError] = useState(""); const [mensaje, setMensaje] = useState(""); const [guardando, setGuardando] = useState(false);
  const cargar = async () => { try { const [lista, config] = await Promise.all([axios.get("/usuarios"), axios.get("/usuarios/config/roles")]); setUsuarios(lista.data); setRoles(config.data.roles); } catch (e) { setError(e.response?.data?.error || "No se pudo cargar la administración de usuarios."); } };
  useEffect(() => { cargar(); }, []);
  const crear = async (e) => { e.preventDefault(); setGuardando(true); setError(""); try { await axios.post("/usuarios", nuevo); setNuevo(inicial); setMensaje("Usuario creado correctamente."); await cargar(); } catch (e) { setError(e.response?.data?.error || "No se pudo crear el usuario."); } finally { setGuardando(false); } };
  const cambiarRol = async (id, rol) => { try { await axios.patch(`/usuarios/${id}/rol`, { rol }); await cargar(); } catch (e) { setError(e.response?.data?.error || "No se pudo actualizar el rol."); } };
  const cambiarEstado = async (id, activo) => { try { await axios.patch(`/usuarios/${id}/activo`, { activo: !activo }); await cargar(); } catch (e) { setError(e.response?.data?.error || "No se pudo actualizar el estado."); } };
  return <section><div className="page-header"><div><h1>Usuarios y permisos</h1><p>Creá cuentas directamente y definí el acceso de cada integrante.</p></div></div>{error && <div className="alert alert-danger">{error}</div>}{mensaje && <div className="alert alert-success">{mensaje}</div>}<div className="row g-4"><div className="col-lg-7"><div className="card"><div className="card-body p-0"><div className="table-responsive"><table className="table mb-0"><thead><tr><th>Usuario</th><th>Rol</th><th>Estado</th><th></th></tr></thead><tbody>{usuarios.map((usuario) => <tr key={usuario.id}><td><strong>{usuario.nombre || usuario.usuario}</strong><br /><small>{usuario.email || usuario.usuario}</small></td><td><select className="form-select form-select-sm" value={usuario.roles[0] || ""} onChange={(e) => cambiarRol(usuario.id, e.target.value)}>{roles.map((rol) => <option key={rol.id} value={rol.clave}>{rol.nombre}</option>)}</select></td><td><span className={`status-badge ${usuario.activo ? "sb-active" : "sb-cancelled"}`}>{usuario.activo ? "Activo" : "Desactivado"}</span></td><td><button type="button" className="btn btn-sm btn-outline-secondary" onClick={() => cambiarEstado(usuario.id, usuario.activo)}>{usuario.activo ? "Desactivar" : "Activar"}</button></td></tr>)}</tbody></table></div></div></div></div><div className="col-lg-5"><div className="card"><div className="card-body"><h2 className="h5">Crear usuario</h2><p className="text-muted small">La persona podrá ingresar con las credenciales que definas ahora.</p><form onSubmit={crear} className="d-grid gap-3"><input className="form-control" placeholder="Nombre completo" value={nuevo.nombre} onChange={(e) => setNuevo({ ...nuevo, nombre: e.target.value })} /><input className="form-control" placeholder="Usuario" value={nuevo.usuario} onChange={(e) => setNuevo({ ...nuevo, usuario: e.target.value })} required /><input className="form-control" type="email" placeholder="Email (opcional)" value={nuevo.email} onChange={(e) => setNuevo({ ...nuevo, email: e.target.value })} /><input className="form-control" type="password" minLength="12" placeholder="Contraseña inicial" value={nuevo.contrasena} onChange={(e) => setNuevo({ ...nuevo, contrasena: e.target.value })} required /><small className="text-muted">12+ caracteres, mayúscula, minúscula, número y símbolo.</small><select className="form-select" value={nuevo.rol} onChange={(e) => setNuevo({ ...nuevo, rol: e.target.value })}>{roles.map((rol) => <option key={rol.id} value={rol.clave}>{rol.nombre}</option>)}</select><button className="btn btn-primary" disabled={guardando}>{guardando ? "Creando..." : "Crear usuario"}</button></form></div></div></div></div></section>;
}
